# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Photographe à Toulouse
email: tom.plessis@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Photographe de mariage, je vis à Bruguières au nord de Toulouse. Je conçois la photographie de mariage à la façon d'un reportage,
  comme une façon d'écrire l'histoire de votre journée.
baseurl: ""
url: "https://www.thomas-plessis.com"
permalink: /:categories/:year/:month/:title.html
twitter_username: tom_plessis
500px_username: peeroflo
facebook_username: T.P.Photographie

# Build settings
markdown: redcarpet

# Gems
gems:
  - jekyll-assets
  - jekyll-srcset-tag

assets:
  cachebust: none
  gzip: true
  compress:
    css: 'sass'
    js: 'uglifier'

  sources:
    - _assets/css
    - _assets/sass
    - _assets/images
    - _assets/fonts
    - _assets/img
    - _assets/js
    - _assets/vendor

srcset:
    source: _assets/images/posts
    output: assets/images/posts/resized

keep_files:
    - assets/images/posts/resized

include: ['.htaccess']
